# Generated by Django 4.1.1 on 2022-10-06 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Course_Name', models.CharField(max_length=50)),
                ('Course_Desc', models.CharField(max_length=255)),
                ('Course_Status', models.CharField(max_length=15)),
                ('Course_Type', models.CharField(max_length=10)),
                ('Course_Category', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('Role_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Role_Name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('Staff_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Staff_FName', models.CharField(max_length=50)),
                ('Staff_LName', models.CharField(max_length=50)),
                ('Dept', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
            options={
                'verbose_name': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('Registration_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Reg_Status', models.CharField(max_length=20)),
                ('Completion_Status', models.CharField(max_length=20)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('Staff_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.staff')),
            ],
            options={
                'verbose_name': 'Registration',
            },
        ),
    ]
