# Generated by Django 4.1.1 on 2022-10-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job_role",
            name="Dept",
            field=models.CharField(default="", max_length=30),
        ),
    ]
