# Generated by Django 4.1.1 on 2022-10-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrole',
            options={'verbose_name': 'Job_Role'},
        ),
        migrations.AlterField(
            model_name='userrole',
            name='UserRole_Name',
            field=models.CharField(max_length=50),
        ),
    ]
