# Generated by Django 4.1.1 on 2022-10-11 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='Job_Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job_role'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='Skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='Staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.staff'),
        ),
    ]
