# Generated by Django 4.1.1 on 2022-10-07 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobrole_skill_rename_role_user_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Role',
            new_name='User_Role',
        ),
        migrations.AddField(
            model_name='course',
            name='Skills',
            field=models.ManyToManyField(to='api.skill'),
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg_Status', models.IntegerField(default=1)),
                ('Completion_Status', models.CharField(max_length=15)),
                ('Job_Role_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.jobrole')),
                ('Skill_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.skill')),
                ('Staff_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.staff')),
            ],
            options={
                'verbose_name': 'Requirements',
                'unique_together': {('Skill_ID', 'Job_Role_ID', 'Staff_ID')},
            },
        ),
    ]
