# Generated by Django 4.1.1 on 2022-10-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_job_role_dept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job_role",
            name="Job_Role_Name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
