# Generated by Django 4.1.1 on 2022-10-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_job_role_job_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="Skills",
            field=models.ManyToManyField(related_name="courses", to="api.skill"),
        ),
    ]
