# Generated by Django 4.1.1 on 2022-10-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_jobrole_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrole',
            old_name='Staff_ID',
            new_name='Staff',
        ),
    ]
