# Generated by Django 4.1.1 on 2022-10-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_job_role_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job_role",
            name="Skills",
            field=models.ManyToManyField(blank=True, to="api.skill"),
        ),
    ]
