# Generated by Django 4.1.1 on 2022-10-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_job_role_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job_role",
            name="Skills",
            field=models.ManyToManyField(
                blank=True, related_name="jb_skills", to="api.skill"
            ),
        ),
    ]
