# Generated by Django 4.1.1 on 2022-10-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_job_role_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="Job_Role",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.job_role",
            ),
        ),
    ]
