# Generated by Django 4.1.1 on 2022-10-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_staff_job_role"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="requirements",
            unique_together={("Job_Role", "Staff")},
        ),
        migrations.RemoveField(
            model_name="requirements",
            name="Course",
        ),
        migrations.AddField(
            model_name="requirements",
            name="Course",
            field=models.ManyToManyField(related_name="ljcourses", to="api.course"),
        ),
    ]
