# Generated by Django 4.1.1 on 2022-10-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_requirements_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requirements",
            old_name="Course",
            new_name="Course_Registered",
        ),
    ]
